// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: salto/nebula/electroniclock/v1/electronic_lock.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Saltoapis.Nebula.ElectronicLock.V1 {
  /// <summary>
  /// An electronic lock is a physical electronic device such as an electronic
  /// escutcheon or cylinder, or a door controller with an electric strike. It
  /// differs from an access point in that, an electronic lock could be a
  /// particular model of a device such as a SALTO Neo cylinder, a door controller
  /// with an electric strike or a Danalock V3 smartlock, for example. An
  /// electronic lock is a single device whereas an access point could be made up
  /// of several devices. An access point could be composed of an electronic lock
  /// plus a door detector, a door controller and a keypad, or an intercom adaptor
  /// which is connected to multiple electronic locks. This service is responsible
  /// for managing electronic lock resources.
  /// </summary>
  public static partial class ElectronicLockService
  {
    static readonly string __ServiceName = "salto.nebula.electroniclock.v1.ElectronicLockService";

    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_ConfigureElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Longrunning.V1.Operation> __Marshaller_salto_longrunning_v1_Operation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Longrunning.V1.Operation.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_CreateElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> __Marshaller_salto_nebula_electroniclock_v1_ElectronicLock = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_DeleteElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_GetElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_InitializeElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest> __Marshaller_salto_nebula_electroniclock_v1_ListElectronicLocksRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse> __Marshaller_salto_nebula_electroniclock_v1_ListElectronicLocksResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_ResetElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest> __Marshaller_salto_nebula_electroniclock_v1_UpdateElectronicLockRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest> __Marshaller_salto_nebula_electroniclock_v1_UpdateElectronicLockFirmwareRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest, global::Saltoapis.Longrunning.V1.Operation> __Method_ConfigureElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest, global::Saltoapis.Longrunning.V1.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConfigureElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_ConfigureElectronicLockRequest,
        __Marshaller_salto_longrunning_v1_Operation);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> __Method_CreateElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_CreateElectronicLockRequest,
        __Marshaller_salto_nebula_electroniclock_v1_ElectronicLock);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_DeleteElectronicLockRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> __Method_GetElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_GetElectronicLockRequest,
        __Marshaller_salto_nebula_electroniclock_v1_ElectronicLock);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest, global::Saltoapis.Longrunning.V1.Operation> __Method_InitializeElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest, global::Saltoapis.Longrunning.V1.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InitializeElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_InitializeElectronicLockRequest,
        __Marshaller_salto_longrunning_v1_Operation);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse> __Method_ListElectronicLocks = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListElectronicLocks",
        __Marshaller_salto_nebula_electroniclock_v1_ListElectronicLocksRequest,
        __Marshaller_salto_nebula_electroniclock_v1_ListElectronicLocksResponse);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest, global::Saltoapis.Longrunning.V1.Operation> __Method_ResetElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest, global::Saltoapis.Longrunning.V1.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResetElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_ResetElectronicLockRequest,
        __Marshaller_salto_longrunning_v1_Operation);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> __Method_UpdateElectronicLock = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest, global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateElectronicLock",
        __Marshaller_salto_nebula_electroniclock_v1_UpdateElectronicLockRequest,
        __Marshaller_salto_nebula_electroniclock_v1_ElectronicLock);

    static readonly grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest, global::Saltoapis.Longrunning.V1.Operation> __Method_UpdateElectronicLockFirmware = new grpc::Method<global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest, global::Saltoapis.Longrunning.V1.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateElectronicLockFirmware",
        __Marshaller_salto_nebula_electroniclock_v1_UpdateElectronicLockFirmwareRequest,
        __Marshaller_salto_longrunning_v1_Operation);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLockReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ElectronicLockService</summary>
    public partial class ElectronicLockServiceClient : grpc::ClientBase<ElectronicLockServiceClient>
    {
      /// <summary>Creates a new client for ElectronicLockService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ElectronicLockServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ElectronicLockService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ElectronicLockServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ElectronicLockServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ElectronicLockServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Configure an electronic lock
      ///
      /// Configures an electronic lock. Configuring an electronic lock implies
      /// adding some information to the electronic lock such as setting the time
      /// zone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation ConfigureElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConfigureElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Configure an electronic lock
      ///
      /// Configures an electronic lock. Configuring an electronic lock implies
      /// adding some information to the electronic lock such as setting the time
      /// zone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation ConfigureElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConfigureElectronicLock, null, options, request);
      }
      /// <summary>
      /// Configure an electronic lock
      ///
      /// Configures an electronic lock. Configuring an electronic lock implies
      /// adding some information to the electronic lock such as setting the time
      /// zone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> ConfigureElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConfigureElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Configure an electronic lock
      ///
      /// Configures an electronic lock. Configuring an electronic lock implies
      /// adding some information to the electronic lock such as setting the time
      /// zone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> ConfigureElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.ConfigureElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConfigureElectronicLock, null, options, request);
      }
      /// <summary>
      /// Create an electronic lock
      ///
      /// Creates a new electronic lock
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock CreateElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create an electronic lock
      ///
      /// Creates a new electronic lock
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock CreateElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateElectronicLock, null, options, request);
      }
      /// <summary>
      /// Create an electronic lock
      ///
      /// Creates a new electronic lock
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> CreateElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create an electronic lock
      ///
      /// Creates a new electronic lock
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> CreateElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.CreateElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateElectronicLock, null, options, request);
      }
      /// <summary>
      /// Delete an electronic lock
      ///
      /// Permanently deletes an electronic lock. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete an electronic lock
      ///
      /// Permanently deletes an electronic lock. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteElectronicLock, null, options, request);
      }
      /// <summary>
      /// Delete an electronic lock
      ///
      /// Permanently deletes an electronic lock. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete an electronic lock
      ///
      /// Permanently deletes an electronic lock. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.DeleteElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteElectronicLock, null, options, request);
      }
      /// <summary>
      /// Get an electronic lock
      ///
      /// Gets an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock GetElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get an electronic lock
      ///
      /// Gets an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock GetElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetElectronicLock, null, options, request);
      }
      /// <summary>
      /// Get an electronic lock
      ///
      /// Gets an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> GetElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get an electronic lock
      ///
      /// Gets an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> GetElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.GetElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetElectronicLock, null, options, request);
      }
      /// <summary>
      /// Initialize an electronic lock
      ///
      /// Initializes an electronic lock. Electronic locks need to be initialized
      /// before you can start to use them.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation InitializeElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitializeElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Initialize an electronic lock
      ///
      /// Initializes an electronic lock. Electronic locks need to be initialized
      /// before you can start to use them.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation InitializeElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InitializeElectronicLock, null, options, request);
      }
      /// <summary>
      /// Initialize an electronic lock
      ///
      /// Initializes an electronic lock. Electronic locks need to be initialized
      /// before you can start to use them.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> InitializeElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitializeElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Initialize an electronic lock
      ///
      /// Initializes an electronic lock. Electronic locks need to be initialized
      /// before you can start to use them.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> InitializeElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.InitializeElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InitializeElectronicLock, null, options, request);
      }
      /// <summary>
      /// List electronic locks
      ///
      /// Returns a list of electronic locks that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse ListElectronicLocks(global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListElectronicLocks(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List electronic locks
      ///
      /// Returns a list of electronic locks that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse ListElectronicLocks(global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListElectronicLocks, null, options, request);
      }
      /// <summary>
      /// List electronic locks
      ///
      /// Returns a list of electronic locks that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse> ListElectronicLocksAsync(global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListElectronicLocksAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List electronic locks
      ///
      /// Returns a list of electronic locks that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksResponse> ListElectronicLocksAsync(global::Saltoapis.Nebula.ElectronicLock.V1.ListElectronicLocksRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListElectronicLocks, null, options, request);
      }
      /// <summary>
      /// Reset an electronic lock
      ///
      /// Resetting a device such as an electronic lock means returning it to its
      /// factory settings. Resetting is the process of removing the identity as
      /// well as all the associated information of an already configured device.
      /// Once a device has been reset, you need to reconfigure it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation ResetElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Reset an electronic lock
      ///
      /// Resetting a device such as an electronic lock means returning it to its
      /// factory settings. Resetting is the process of removing the identity as
      /// well as all the associated information of an already configured device.
      /// Once a device has been reset, you need to reconfigure it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation ResetElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResetElectronicLock, null, options, request);
      }
      /// <summary>
      /// Reset an electronic lock
      ///
      /// Resetting a device such as an electronic lock means returning it to its
      /// factory settings. Resetting is the process of removing the identity as
      /// well as all the associated information of an already configured device.
      /// Once a device has been reset, you need to reconfigure it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> ResetElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Reset an electronic lock
      ///
      /// Resetting a device such as an electronic lock means returning it to its
      /// factory settings. Resetting is the process of removing the identity as
      /// well as all the associated information of an already configured device.
      /// Once a device has been reset, you need to reconfigure it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> ResetElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.ResetElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResetElectronicLock, null, options, request);
      }
      /// <summary>
      /// Update an electronic lock
      ///
      /// Updates an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock UpdateElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateElectronicLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update an electronic lock
      ///
      /// Updates an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock UpdateElectronicLock(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateElectronicLock, null, options, request);
      }
      /// <summary>
      /// Update an electronic lock
      ///
      /// Updates an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> UpdateElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateElectronicLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update an electronic lock
      ///
      /// Updates an existing electronic lock.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ElectronicLock.V1.ElectronicLock> UpdateElectronicLockAsync(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateElectronicLock, null, options, request);
      }
      /// <summary>
      /// Update electronic lock firmware
      ///
      /// Updates an electronic lock's firmware. SALTO provides firmware updates
      /// when new functionality is available or when we fix a bug.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation UpdateElectronicLockFirmware(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateElectronicLockFirmware(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update electronic lock firmware
      ///
      /// Updates an electronic lock's firmware. SALTO provides firmware updates
      /// when new functionality is available or when we fix a bug.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Saltoapis.Longrunning.V1.Operation UpdateElectronicLockFirmware(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateElectronicLockFirmware, null, options, request);
      }
      /// <summary>
      /// Update electronic lock firmware
      ///
      /// Updates an electronic lock's firmware. SALTO provides firmware updates
      /// when new functionality is available or when we fix a bug.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> UpdateElectronicLockFirmwareAsync(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateElectronicLockFirmwareAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update electronic lock firmware
      ///
      /// Updates an electronic lock's firmware. SALTO provides firmware updates
      /// when new functionality is available or when we fix a bug.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Longrunning.V1.Operation> UpdateElectronicLockFirmwareAsync(global::Saltoapis.Nebula.ElectronicLock.V1.UpdateElectronicLockFirmwareRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateElectronicLockFirmware, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ElectronicLockServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ElectronicLockServiceClient(configuration);
      }
    }

  }
}
#endregion
