load("//:rules.bzl", "load_rules")

package(default_visibility = ['//:__subpackages__'])

load_rules(
    lib_name = 'Saltoapis.Auth',
    internal_dependencies = [
    ],
    extra_info = {
        'nuget_description': 'Saltoapis Authentication Library handles authentication with Nebula.'
    },
)
