// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: salto/nebula/serviceaccount/v1/service_account.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Saltoapis.Nebula.ServiceAccount.V1 {
  /// <summary>
  /// A service account is a specialized account used by applications or services to
  /// authenticate and interact with other applications or services, providing a secure
  /// and controlled way to manage access to resources.
  /// </summary>
  public static partial class ServiceAccountService
  {
    static readonly string __ServiceName = "salto.nebula.serviceaccount.v1.ServiceAccountService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest> __Marshaller_salto_nebula_serviceaccount_v1_CreateServiceAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccount = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest> __Marshaller_salto_nebula_serviceaccount_v1_GetServiceAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest> __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse> __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest> __Marshaller_salto_nebula_serviceaccount_v1_UpdateServiceAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest> __Marshaller_salto_nebula_serviceaccount_v1_DeleteServiceAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest> __Marshaller_salto_nebula_serviceaccount_v1_CreateServiceAccountKeyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccountKey = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest> __Marshaller_salto_nebula_serviceaccount_v1_GetServiceAccountKeyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest> __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountKeysRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse> __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountKeysResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest> __Marshaller_salto_nebula_serviceaccount_v1_DeleteServiceAccountKeyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> __Method_CreateServiceAccount = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateServiceAccount",
        __Marshaller_salto_nebula_serviceaccount_v1_CreateServiceAccountRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccount);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> __Method_GetServiceAccount = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetServiceAccount",
        __Marshaller_salto_nebula_serviceaccount_v1_GetServiceAccountRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccount);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse> __Method_ListServiceAccounts = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListServiceAccounts",
        __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountsRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> __Method_UpdateServiceAccount = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateServiceAccount",
        __Marshaller_salto_nebula_serviceaccount_v1_UpdateServiceAccountRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccount);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteServiceAccount = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteServiceAccount",
        __Marshaller_salto_nebula_serviceaccount_v1_DeleteServiceAccountRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> __Method_CreateServiceAccountKey = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateServiceAccountKey",
        __Marshaller_salto_nebula_serviceaccount_v1_CreateServiceAccountKeyRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccountKey);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> __Method_GetServiceAccountKey = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetServiceAccountKey",
        __Marshaller_salto_nebula_serviceaccount_v1_GetServiceAccountKeyRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ServiceAccountKey);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse> __Method_ListServiceAccountKeys = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest, global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListServiceAccountKeys",
        __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountKeysRequest,
        __Marshaller_salto_nebula_serviceaccount_v1_ListServiceAccountKeysResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteServiceAccountKey = new grpc::Method<global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteServiceAccountKey",
        __Marshaller_salto_nebula_serviceaccount_v1_DeleteServiceAccountKeyRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ServiceAccountService</summary>
    public partial class ServiceAccountServiceClient : grpc::ClientBase<ServiceAccountServiceClient>
    {
      /// <summary>Creates a new client for ServiceAccountService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServiceAccountServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ServiceAccountService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServiceAccountServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServiceAccountServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServiceAccountServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Create a service account
      ///
      /// Creates a new service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount CreateServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateServiceAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a service account
      ///
      /// Creates a new service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount CreateServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateServiceAccount, null, options, request);
      }
      /// <summary>
      /// Create a service account
      ///
      /// Creates a new service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> CreateServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateServiceAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a service account
      ///
      /// Creates a new service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> CreateServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateServiceAccount, null, options, request);
      }
      /// <summary>
      /// Get a service account
      ///
      /// Retrieves an existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount GetServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServiceAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get a service account
      ///
      /// Retrieves an existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount GetServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetServiceAccount, null, options, request);
      }
      /// <summary>
      /// Get a service account
      ///
      /// Retrieves an existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> GetServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServiceAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get a service account
      ///
      /// Retrieves an existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> GetServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetServiceAccount, null, options, request);
      }
      /// <summary>
      /// List service accounts
      ///
      /// Returns a list of service accounts that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse ListServiceAccounts(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListServiceAccounts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List service accounts
      ///
      /// Returns a list of service accounts that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse ListServiceAccounts(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListServiceAccounts, null, options, request);
      }
      /// <summary>
      /// List service accounts
      ///
      /// Returns a list of service accounts that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse> ListServiceAccountsAsync(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListServiceAccountsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List service accounts
      ///
      /// Returns a list of service accounts that have been previously created.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsResponse> ListServiceAccountsAsync(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListServiceAccounts, null, options, request);
      }
      /// <summary>
      /// Update the service account
      ///
      /// Updates the existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount UpdateServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateServiceAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update the service account
      ///
      /// Updates the existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount UpdateServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateServiceAccount, null, options, request);
      }
      /// <summary>
      /// Update the service account
      ///
      /// Updates the existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> UpdateServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateServiceAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update the service account
      ///
      /// Updates the existing service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccount> UpdateServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.UpdateServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateServiceAccount, null, options, request);
      }
      /// <summary>
      /// Delete a service account
      ///
      /// Permanently deletes a service account. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteServiceAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a service account
      ///
      /// Permanently deletes a service account. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteServiceAccount(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteServiceAccount, null, options, request);
      }
      /// <summary>
      /// Delete a service account
      ///
      /// Permanently deletes a service account. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteServiceAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a service account
      ///
      /// Permanently deletes a service account. This cannot be undone.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteServiceAccountAsync(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteServiceAccount, null, options, request);
      }
      /// <summary>
      /// Create a service account key
      ///
      /// Creates a new service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey CreateServiceAccountKey(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateServiceAccountKey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a service account key
      ///
      /// Creates a new service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey CreateServiceAccountKey(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateServiceAccountKey, null, options, request);
      }
      /// <summary>
      /// Create a service account key
      ///
      /// Creates a new service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> CreateServiceAccountKeyAsync(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateServiceAccountKeyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a service account key
      ///
      /// Creates a new service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> CreateServiceAccountKeyAsync(global::Saltoapis.Nebula.ServiceAccount.V1.CreateServiceAccountKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateServiceAccountKey, null, options, request);
      }
      /// <summary>
      /// Get a service account key
      ///
      /// Retrieves a specific service account key by its resource name.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey GetServiceAccountKey(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServiceAccountKey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get a service account key
      ///
      /// Retrieves a specific service account key by its resource name.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey GetServiceAccountKey(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetServiceAccountKey, null, options, request);
      }
      /// <summary>
      /// Get a service account key
      ///
      /// Retrieves a specific service account key by its resource name.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> GetServiceAccountKeyAsync(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServiceAccountKeyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get a service account key
      ///
      /// Retrieves a specific service account key by its resource name.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ServiceAccountKey> GetServiceAccountKeyAsync(global::Saltoapis.Nebula.ServiceAccount.V1.GetServiceAccountKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetServiceAccountKey, null, options, request);
      }
      /// <summary>
      /// List service account keys
      ///
      /// Returns a list of keys for a service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse ListServiceAccountKeys(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListServiceAccountKeys(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List service account keys
      ///
      /// Returns a list of keys for a service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse ListServiceAccountKeys(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListServiceAccountKeys, null, options, request);
      }
      /// <summary>
      /// List service account keys
      ///
      /// Returns a list of keys for a service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse> ListServiceAccountKeysAsync(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListServiceAccountKeysAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// List service account keys
      ///
      /// Returns a list of keys for a service account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysResponse> ListServiceAccountKeysAsync(global::Saltoapis.Nebula.ServiceAccount.V1.ListServiceAccountKeysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListServiceAccountKeys, null, options, request);
      }
      /// <summary>
      /// Delete a service account key
      ///
      /// Permanently deletes a service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteServiceAccountKey(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteServiceAccountKey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a service account key
      ///
      /// Permanently deletes a service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteServiceAccountKey(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteServiceAccountKey, null, options, request);
      }
      /// <summary>
      /// Delete a service account key
      ///
      /// Permanently deletes a service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteServiceAccountKeyAsync(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteServiceAccountKeyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a service account key
      ///
      /// Permanently deletes a service account key.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteServiceAccountKeyAsync(global::Saltoapis.Nebula.ServiceAccount.V1.DeleteServiceAccountKeyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteServiceAccountKey, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ServiceAccountServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServiceAccountServiceClient(configuration);
      }
    }

  }
}
#endregion
