// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: salto/nebula/type/device_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Saltoapis.Nebula.Type {

  /// <summary>Holder for reflection information generated from salto/nebula/type/device_type.proto</summary>
  public static partial class DeviceTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for salto/nebula/type/device_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DeviceTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzYWx0by9uZWJ1bGEvdHlwZS9kZXZpY2VfdHlwZS5wcm90bxIRc2FsdG8u",
            "bmVidWxhLnR5cGUqjAEKCkRldmljZVR5cGUSGwoXREVWSUNFX1RZUEVfVU5T",
            "UEVDSUZJRUQQABITCg9FTEVDVFJPTklDX0xPQ0sQARILCgdHQVRFV0FZEAIS",
            "DAoIRVhURU5ERVIQAxILCgdFTkNPREVSEAQSDgoKQ09OVFJPTExFUhAFEhQK",
            "EElOVEVSQ09NX0FEQVBUT1IQBkKTAQoZY29tLnNhbHRvYXBpcy5uZWJ1bGEu",
            "dHlwZUIPRGV2aWNlVHlwZVByb3RvUAFaS2dpdGh1Yi5jb20vcHJpdmF0ZS1z",
            "YWx0b2FwaXMvc2FsdG9hcGlzLWdvL25lYnVsYS90eXBlL2RldmljZXR5cGU7",
            "ZGV2aWNldHlwZaoCFVNhbHRvYXBpcy5OZWJ1bGEuVHlwZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Saltoapis.Nebula.Type.DeviceType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Represents the device types.
  /// </summary>
  public enum DeviceType {
    /// <summary>
    /// Unspecified
    /// </summary>
    [pbr::OriginalName("DEVICE_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Electronic lock
    /// </summary>
    [pbr::OriginalName("ELECTRONIC_LOCK")] ElectronicLock = 1,
    /// <summary>
    /// Gateway
    /// </summary>
    [pbr::OriginalName("GATEWAY")] Gateway = 2,
    /// <summary>
    /// Extender
    /// </summary>
    [pbr::OriginalName("EXTENDER")] Extender = 3,
    /// <summary>
    /// Encoder
    /// </summary>
    [pbr::OriginalName("ENCODER")] Encoder = 4,
    /// <summary>
    /// Controller
    /// </summary>
    [pbr::OriginalName("CONTROLLER")] Controller = 5,
    /// <summary>
    /// Intercom Adaptor
    /// </summary>
    [pbr::OriginalName("INTERCOM_ADAPTOR")] IntercomAdaptor = 6,
  }

  #endregion

}

#endregion Designer generated code
