// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: salto/nebula/types/v1/day_of_week.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Saltoapis.Nebula.Types.V1 {

  /// <summary>Holder for reflection information generated from salto/nebula/types/v1/day_of_week.proto</summary>
  public static partial class DayOfWeekReflection {

    #region Descriptor
    /// <summary>File descriptor for salto/nebula/types/v1/day_of_week.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DayOfWeekReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidzYWx0by9uZWJ1bGEvdHlwZXMvdjEvZGF5X29mX3dlZWsucHJvdG8SFXNh",
            "bHRvLm5lYnVsYS50eXBlcy52MSqEAQoJRGF5T2ZXZWVrEhsKF0RBWV9PRl9X",
            "RUVLX1VOU1BFQ0lGSUVEEAASCgoGTU9OREFZEAESCwoHVFVFU0RBWRACEg0K",
            "CVdFRE5FU0RBWRADEgwKCFRIVVJTREFZEAQSCgoGRlJJREFZEAUSDAoIU0FU",
            "VVJEQVkQBhIKCgZTVU5EQVkQB0KXAQodY29tLnNhbHRvYXBpcy5uZWJ1bGEu",
            "dHlwZXMudjFCDkRheU9mV2Vla1Byb3RvUAFaSGdpdGxhYi5ybmQuc2FsdG9z",
            "eXN0ZW1zLmNvbS9zYWx0b2FwaXMvc2FsdG9hcGlzLWdvL25lYnVsYS90eXBl",
            "cy92MTt0eXBlc6oCGVNhbHRvYXBpcy5OZWJ1bGEuVHlwZXMuVjFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Saltoapis.Nebula.Types.V1.DayOfWeek), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Represents a day of week.
  /// </summary>
  public enum DayOfWeek {
    /// <summary>
    /// Unspecified
    /// </summary>
    [pbr::OriginalName("DAY_OF_WEEK_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Monday
    /// </summary>
    [pbr::OriginalName("MONDAY")] Monday = 1,
    /// <summary>
    /// Tuesday
    /// </summary>
    [pbr::OriginalName("TUESDAY")] Tuesday = 2,
    /// <summary>
    /// Wednesday
    /// </summary>
    [pbr::OriginalName("WEDNESDAY")] Wednesday = 3,
    /// <summary>
    /// Thursday
    /// </summary>
    [pbr::OriginalName("THURSDAY")] Thursday = 4,
    /// <summary>
    /// Friday
    /// </summary>
    [pbr::OriginalName("FRIDAY")] Friday = 5,
    /// <summary>
    /// Saturday
    /// </summary>
    [pbr::OriginalName("SATURDAY")] Saturday = 6,
    /// <summary>
    /// Sunday
    /// </summary>
    [pbr::OriginalName("SUNDAY")] Sunday = 7,
  }

  #endregion

}

#endregion Designer generated code
